[package]
name = "ranma-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ranma"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "0.2"
argh = "0.1"
